---
title: 'Fun with ChatAO: Covid Prophet'
author: "David Jackson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSQLite)
library(prophet)
library(scales)
library(plotly)
```
```{r}
# Connect to the database
con <- dbConnect(SQLite(), dbname = "C:/Users/david/Documents/R/COVID-19-DB/OURWORLD.sqlite3")

# Read the data into R
data <- dbGetQuery(con, "SELECT date,total_cases,total_deaths FROM pandemic WHERE iso_code ='USA'")
data$date <- as.Date(data$date)
str(data)

# Disconnect from the database
dbDisconnect(con)
```
## The Prophet Has Spoken

#### Cumulative Totals To Date

```{r}
ggplot(data=data,aes(x=date,y=total_cases)) + geom_line() +
  scale_y_continuous(labels = comma)
```


```{r}

# Load your data into R
# covid_data <- read.csv("path/to/your/covid_data.csv")

# Format the data for use with prophet
# Prophet requires a data frame with two columns: ds (the date) and y (the response variable)
covid_data_prophet <- data.frame(ds = as.Date(data$date), y = data$total_cases)
```
```{r}
# Fit the prophet model
model <- prophet(covid_data_prophet)

# Generate future predictions
# future <- make_future_dataframe(model, periods = 365)
future <- make_future_dataframe(model, periods = 90)
forecast <- predict(model, future)
```
```{r}
# Plot the results
plot(model, forecast) + scale_y_continuous(labels = comma)

```


```{r}

max_yhat <- max(forecast$yhat)
max_yhat_date <- forecast$ds[which.max(forecast$yhat)]

forecast %>% filter(ds >="2022-02-09") %>%
ggplot() +
  geom_line(aes(x = ds, y = yhat, col = "Prediction")) +
  geom_ribbon(aes(x = ds, ymin = yhat_lower, ymax = yhat_upper), fill = "gray", alpha =0.8) +
  labs(x = "Date", y = "Total Cases",title = "Prediction for Total Case as of May 8, 2023") +
  scale_color_manual(values = c("Prediction" = "red")) +
  geom_text(x = max_yhat_date, y = max_yhat, label = paste("Max:", format(round(max_yhat), big.mark = ",")), hjust = 1.5, vjust = -0.5, color = "blue") +
   theme_classic() +
  theme(
    panel.grid.major = element_line(color = "gray70"),
    panel.grid.minor = element_line(color = "gray90")
  )
```

#### Cumulative Totals Deaths To Date

```{r}
ggplot(data=data,aes(x=date,y=total_deaths)) + geom_line() +
  scale_y_continuous(labels = comma)
```

#### Prediction Cumulative Deaths

```{r}

# Load your data into R
# covid_data <- read.csv("path/to/your/covid_data.csv")

# Format the data for use with prophet
# Prophet requires a data frame with two columns: ds (the date) and y (the response variable)
covid_data_deaths <- data.frame(ds = as.Date(data$date), y = data$total_deaths)
```
```{r}
# Fit the prophet model
model1 <- prophet(covid_data_deaths)

# Generate future predictions
# future <- make_future_dataframe(model, periods = 365)
future1 <- make_future_dataframe(model, periods = 90)
forecast1 <- predict(model1, future1)
```
```{r}
# Plot the results
plot(model1, forecast1)+ scale_y_continuous(labels = comma)

```


```{r}

max_yhat <- max(forecast$yhat)
max_yhat_date <- forecast$ds[which.max(forecast$yhat)]

forecast %>% filter(ds >= "2022-02-09") %>%
ggplot() +
  geom_line(aes(x = ds, y = yhat, col = "Prediction")) +
  geom_ribbon(aes(x = ds, ymin = yhat_lower, ymax = yhat_upper), fill = "gray", alpha = 0.8) +
  labs(x = "Date", y = "Total Cases", title = "Prediction for Total Cases By May 8, 2023") +
  scale_color_manual(values = c("Prediction" = "red")) +
  geom_text(x = max_yhat_date, y = max_yhat, label = paste("Max:", format(round(max_yhat), big.mark = ",")), hjust = 1.5, vjust = -0.5, color = "blue") +
  scale_y_continuous(labels = comma) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(color = "gray"),
    panel.grid.minor = element_line(color = "gray")
  )

```

```{r}
max_yhat <- max(forecast1$yhat)
max_yhat_date <- forecast1$ds[which.max(forecast1$yhat)]

forecast1 %>% filter(ds >= "2022-02-09") %>%
ggplot() +
  geom_line(aes(x = ds, y = yhat, col = "Prediction")) +
  geom_ribbon(aes(x = ds, ymin = yhat_lower, ymax = yhat_upper), fill = "gray", alpha = 0.8) +
  labs(x = "Date", y = "Total Deaths", title = "Prediction for Total Deaths By May 8, 2023") +
  scale_color_manual(values = c("Prediction" = "red")) +
  geom_text(x = max_yhat_date, y = max_yhat, label = paste("Max:", format(round(max_yhat), big.mark = ",")), hjust = 1.5, vjust = -0.5, color = "blue") +
  scale_y_continuous(labels = comma) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(color = "gray"),
    panel.grid.minor = element_line(color = "gray")
  )

```

